name: Testes Android

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      android_emulator:
        type: choice
        description: Selecione um emulador Android
        required: true
        options:
          - pixel_5
          - pixel_6
        default: pixel_5

permissions:
  contents: write
  pages: write
  id-token: write

env:
  API_LEVEL: 32
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis
  ANDROID_BUILD_TOOLS_VERSION: 34.0.0

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Habilitar KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Instalar dependências
        run: npm i

      - name: Encontrar o arquivo APK
        run: find . -name "*.apk"

      - name: Executar testes Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          target: google_apis_playstore
          arch: x86_64
          profile: ${{ github.event.inputs.android_emulator || 'pixel_5' }}
          script: |
            adb install ./app/Android-NativeDemoApp-0.4.0.apk
            npm run android

      - name: Gerar relatório Allure
        if: always()
        run: |
          npm install -g allure-commandline
          npx allure generate allure-results --clean -o allure-report
          
      - name: Publicar no GitHub Pages
        if: always()
        uses: actions/upload-pages-artifact@v4
        with:
          path: './allure-report'
      - id: deployment
        uses: actions/deploy-pages@v4