name: Testes Android

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      android_emulator:
        type: choice
        description: Selecione um emulador Android
        required: true
        options:
          - Nexus_5
          - Nexus_6
        default: Nexus_5

permissions:
  contents: write
  pages: write
  id-token: write

env:
  API_LEVEL: 32
  EMULATOR_NAME: ${{ inputs.android_emulator || 'Nexus_5' }}
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis
  ANDROID_BUILD_TOOLS_VERSION: 34.0.0
  EMULATOR_TIMEOUT: 350
  BOOT_TIMEOUT: 700

jobs:
  android:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Executar testes Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          target: google_apis_playstore
          arch: x86_64
          profile: ${{ env.EMULATOR_NAME }}
          script: |
            npm i
            adb install ./app/Android-NativeDemoApp-0.4.0.apk
            npm run android

      - name: Gerar relatório Allure
        if: always()
        run: |
          npm install -g allure-commandline
          npx allure generate allure-results --clean -o allure-report
          
      - name: Configurar e publicar no GitHub Pages
        if: always()
        uses: actions/upload-pages-artifact@v4
        with:
          path: './allure-report'
      - id: deployment
        uses: actions/deploy-pages@v4